version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=your_redis_password
  
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=your_redis_password
      - REDIS_DB=0
      - DEFAULT_IP_LIMIT=10
      - DEFAULT_IP_BLOCK_TIME_SECONDS=60
      - SERVER_PORT=8080
    depends_on:
      - redis

volumes:
  redis_data: